name: iSEC Research Labs
markdown: redcarpet
pygments: true
description: iSEC's engineers often release open-source tools, whitepapers, and research presentations as part of our work. This is where we keep them.
url: https://isecpartners.github.io/
paginate: 5
